version: '3.3'

services:
  productpage:
    build:
      context: .
      dockerfile: ProductPage_Dockerfile
    image: grupo48/productpage
    restart: always
    ports:
      - 9080:9080
    links:
      - details
      - reviews

  details:
    build:
      context: .
      dockerfile: Details_Dockerfile
    image: grupo48/details
    restart: always
    expose:
      - 9080
  
  reviews:
    build:
      context: .
      dockerfile: Reviews_Dockerfile3
    image: grupo48/reviews
    restart: always
    expose:
      - 9080
    links:
      - ratings

  ratings:
    build:
      context: .
      dockerfile: Ratings_Dockerfile
    image: grupo48/ratings
    restart: always
    expose:
      - 9080
